---
date_stamp: "{{ ansible_date_time.date }}"
time_stamp: "{{ ansible_date_time.time |replace(':','')}}"
datetime_stamp: "{{ date_stamp }}-{{ time_stamp }}"
local_home: "{{ lookup('env', 'HOME') }}"
